### ISSUE TITLE
Add a means of getting preferences from browser

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#1]
We need a way of getting to things like:

``` JS
Services.prefs.getIntPref("browser.newtabpage.rows")
```

So we can having to hard-coding these values int the tiles grid generation code. 

Need to add the additonal prefs here: 
- [x] browser.newtabpage.enhanced
- [x] browser.newtabpage.rows
- [x] browser.newtabpage.enabled

**Comment by emtwo** [comment]
Fixed by pull request #8
