### ISSUE TITLE
locale/newTab.js should be an JSON file

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#114]
we should load newTab.js strings as needed, using fetch as XML.

**Comment by marcoscaceres** [comment]
Loosely depends on: 
https://github.com/whatwg/fetch/issues/151

**Comment by marcoscaceres** [comment]
Can do:

``` JS
async function fetchXML(url){
  var response = await fetch(url);
  var text = await response.text(); 
  return (new DOMParser()).parseFromString(text, "text/xml");
}
```

**Comment by oyiptong** [comment]
Any reason why we want locale/newTab.js as XML?
We can make it JSON.

If we re-use the XML as-is currently, there is a need for 2 requests: the xml and the DTD which actually contains the text:

http://mxr.mozilla.org/l10n-central/source/en-GB/browser/chrome/browser/newTab.dtd
http://mxr.mozilla.org/l10n-central/source/en-GB/browser/chrome/browser/newTab.properties

There is also no locale XML for en-US in l10n-central.

How about we provide one JSON file per locale, generated as a build step?

**Comment by marcoscaceres** [comment]
(Note, this is a v2 thing)

> On Nov 3, 2015, at 3:14 AM, Olivier Yiptong notifications@github.com wrote:
> 
> Any reason why we want locale/newTab.js as XML?
> We can make it JSON
> 
> That would be great - just need to remove the comments. Right now, anyone localizing could add arbitrary code to the locales file, which makes me a bit uncomfortable. This could break things, or worse, obviously.
> If we re-use the XML as-is currently, there is a need for 2 requests: the xml and the DTD which actually contains the text:
> 
> http://mxr.mozilla.org/l10n-central/source/en-GB/browser/chrome/browser/newTab.dtd
> http://mxr.mozilla.org/l10n-central/source/en-GB/browser/chrome/browser/newTab.properties

Yeah, the currently used format is pretty awful.
