### ISSUE TITLE
Implement localization + automation

### ISSUE THREAD

**Issue by oyiptong** [mozilla/remote-newtab#126]
- [x] Obtain the 104 language files from the l10n and generate language files
- [x] Create automation for the building of the l10n-aware distributions
- [ ] Create import structure for files so we don't produce too many artifacts for deployment

**Comment by marcoscaceres** [comment]
I've added support for verifying the l10n data. There are [significant gaps](https://gist.github.com/marcoscaceres/4c0e4a360cb8a44ea900), which I'm plugging with en-US content. 

Unfortunately, it won't be possible to do "lookup" to fill the gaps, because only like 2 locales provide such an ability. That's ok tho. We can just file bugs for everything and see if the localizers can find people to fill the gaps for us.

**Comment by marcoscaceres** [comment]
The following files are 404:
- http://mxr.mozilla.org/l10n-central/source/st/browser/chrome/browser/newTab.dtd?raw=1
- http://mxr.mozilla.org/l10n-central/source/nr/browser/chrome/browser/newTab.dtd?raw=1
- http://mxr.mozilla.org/l10n-central/source/nr/browser/chrome/browser/newTab.properties?raw=1
- http://mxr.mozilla.org/l10n-central/source/ts/browser/chrome/browser/newTab.dtd?raw=1
- http://mxr.mozilla.org/l10n-central/source/ve/browser/chrome/browser/newTab.dtd?raw=1
- http://mxr.mozilla.org/l10n-central/source/ts/browser/chrome/browser/newTab.properties?raw=1
- http://mxr.mozilla.org/l10n-central/source/st/browser/chrome/browser/newTab.properties?raw=1
- http://mxr.mozilla.org/l10n-central/source/ss/browser/chrome/browser/newTab.dtd?raw=1
- http://mxr.mozilla.org/l10n-central/source/ss/browser/chrome/browser/newTab.properties?raw=1
- http://mxr.mozilla.org/l10n-central/source/ve/browser/chrome/browser/newTab.properties?raw=1

**Comment by oyiptong** [comment]
boo. we could also procure the raw .lang files. it would be just a tiny bit more work than parsing the xml

edit: I spoke to l10n'ers and it looks like they have localizations coming from various sources. the source of truth should be those xml+dtd files

**Comment by oyiptong** [comment]
actually
instead of trying to obtain them from mxr
why not obtain them from hg?

**Comment by oyiptong** [comment]
spoke to Aryx and Pike on irc.

Here's where we should get the localizations: http://hg.mozilla.org/releases/l10n/mozilla-aurora

Apparently, localizers prefer to work on Aurora. Presumably because nightly code changes too much.

**Comment by oyiptong** [comment]
To be more precise, the list of shipping localizations is here:
https://hg.mozilla.org/releases/mozilla-aurora/raw-file/tip/browser/locales/shipped-locales

Based on those localizations, we can construct HTTP fetches based on this URL structure:

For en-US:

https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/locales/en-US/chrome/browser/newTab.dtd
https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/locales/en-US/chrome/browser/newTab.properties

For the rest:
https://hg.mozilla.org/releases/l10n/mozilla-aurora/en-GB/raw-file/tip/browser/chrome/browser/newTab.dtd
https://hg.mozilla.org/releases/l10n/mozilla-aurora/en-GB/raw-file/tip/browser/chrome/browser/newTab.properties

This should be a small addition + modification for code in #136

**Comment by oyiptong** [comment]
checking it out a couple of cases:

locale "st" is missing from https://hg.mozilla.org/releases/mozilla-aurora/raw-file/tip/browser/locales/shipped-locales, therefore shouldn't have a corresponding l10n.

from https://gist.github.com/marcoscaceres/4c0e4a360cb8a44ea900#file-l10n_gaps-log-L10-L69, which was missing from mxr:

```
$ curl https://hg.mozilla.org/releases/l10n/mozilla-aurora/be/raw-file/tip/browser/chrome/browser/newTab.properties
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

newtab.pin = Прышпіліць пляцоўку на цяперашняе месца
newtab.unpin = Адшпіліць пляцоўку
newtab.block = Прыняць гэтую пляцоўку
newtab.show = Паказаць старонку новай устаўкі
newtab.hide = Схаваць старонку новай устаўкі
newtab.sponsored = Паказваць звесткі ў праплачаных чарапічынах
oyiptong@quanta:~/temp$ curl https://hg.mozilla.org/releases/l10n/mozilla-aurora/be/raw-file/tip/browser/chrome/browser/newTab.dtd
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->

<!ENTITY newtab.pageTitle "Новая ўстаўка">
<!ENTITY newtab.undo.removedLabel "Накід выдалены.">
<!ENTITY newtab.undo.undoButton "Адмяніць.">
<!ENTITY newtab.undo.restoreButton "Вярнуць усё.">
<!ENTITY newtab.undo.closeTooltip "Схаваць">
<!ENTITY newtab.sponsored.release.message "Прапаноўваецца гэтая праплачаная пляцоўка, бо мы спадзяваемся, што яна цікавая вам, і таму, што праплатчык падтрымлівае місію Mozilla.">
<!ENTITY newtab.sponsored.trial.message "Прапаноўваецца гэтая спробная праплачаная пляцоўка, бо мы спадзяваемся, што яна цікавая вам, і таму, што праплатчык падтрымлівае місію Mozilla.">
<!ENTITY newtab.panel.link.text "Падрабязней…">
```

**Comment by k88hudson** [comment]
Moving to new ticket
