### ISSUE TITLE
Container document messaging

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#13]
The remote newTab page needs to be an iframe in a container document reachable at `about:newTab`. The container document handle message passing. 
- [ ] rename "newTab.html" -> index.html
- [ ] make a new "newTab.html" that contains the `<iframe>` pointing to the remote site,  and sets up message handling.

**Comment by oyiptong** [comment]
Marina has the second piece in a repo outside of this one, tracked by [bug 1183206](https://bugzilla.mozilla.org/show_bug.cgi?id=1183206)

**Comment by marcoscaceres** [comment]
Ah, awesome!

**Comment by marcoscaceres** [comment]
Would anyone object to renaming "newTab.html"  to "index.html"?

**Comment by oyiptong** [comment]
+1 to index.html
