### ISSUE TITLE
locale should be obtained from URL

### ISSUE THREAD

**Issue by oyiptong** [mozilla/remote-newtab#191]
`locale` should be obtained from the URL and not from a pref, as per https://github.com/mozilla/remote-newtab/blob/d7ba21c494dd1863223cc022606e878d9ed3fb25/src/reducers/PrefsReducer.js#L14

This is because the pref for locales is not the only determinant.

The algorithm is described in: https://dxr.mozilla.org/mozilla-central/rev/aa90f482e16db77cdb7dea84564ea1cbd8f7f6b3/toolkit/modules/Locale.jsm#20

We use the result of this function to set the URL of the page

**Comment by k88hudson** [comment]
This is what is currently implemented here, sorry, there are some extraneous prefs in the test data
The locale data gets built into a separate file during the build process and imported here https://github.com/mozilla/remote-newtab/blob/master/src/main.js#L17
:+1:
