### ISSUE TITLE
fix all invalid attribute calls in .js files

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#21]
customize.js sets a non-conforming "open" attribute. It should use `data-open` instead + HTML data API.

**Comment by marcoscaceres** [comment]
It also sets `active`.

**Comment by sarracini** [comment]
I noticed it also sets a "selected" attribute. Should we be using `data-selected` as well?

**Comment by marcoscaceres** [comment]
There are a bunch of these... just grep `removeAttribute`

**Comment by marcoscaceres** [comment]
To directly answer your question, yes :) We should not be adding random attributes or abusing existing ones.
