### ISSUE TITLE
Text direction and localized content should be merged

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#39]
In the current version of the newTab page, there is a `global.dtd` file that contains the direction of firefox's UI. We should merge that into the data of `newTab.dtd`... doing so will allow us to generate localized pages with a single pass on the server.

**Comment by sarracini** [comment]
While we're at it, the remote page needs to be rtl friendly, which it isn't right now so I'll also be doing that as well

**Comment by marcoscaceres** [comment]
FWIW, the dir was getting set when the l10n files were being generated. Did that regress?

**Comment by marcoscaceres** [comment]
(oh, I see in a different bug that the views/l10n are handled by react now...)
