### ISSUE TITLE
Drop pinning... 

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#88]
Pinning is confusing and seems pretty useless. Can we get some numbers to see if anyone actually uses it?

**Comment by oyiptong** [comment]
It isn't used much. It is used much less than clicks. However, we don't want to drop it just yet.

We want the functionality to be 1:1 at first, then we switch things up

**Comment by oyiptong** [comment]
```csv
date,tile_id,impressions,clicks,blocked,pinned,sponsored,sponsored_link
2015-08-25,2598,10879837,10768,144184,207,230,19
2015-08-26,2598,10807658,9159,98442,161,213,14
2015-08-31,1347,10274612,5227,31559,127,0,0
2015-08-31,1944,10219923,4109,27442,148,0,0
2015-08-25,1347,9986834,5144,31642,145,0,0
2015-08-26,1347,9962478,5488,31194,136,0,0
2015-08-25,1944,9892553,4241,27003,129,0,0
2015-08-26,1944,9881127,4110,26886,136,0,0
2015-08-24,1347,9842035,5567,30520,143,0,0
2015-08-27,1347,9788515,5085,30152,137,0,0
```

**Comment by marcoscaceres** [comment]
Sure, this would be a v2 thing.

**Comment by mzhilyaev** [comment]
Regular pins are OK, but pinning because of a drag/drop is a royal pain in the ....  (you know where).
If you have an exact behavior that you want to fix, I can definitely look.

**Comment by marcoscaceres** [comment]
@mzhilyaev, we want to work with the products folks to hopefully drop the feature entirely. We need some definitive data to show that pinning is rarely used.

**Comment by mzhilyaev** [comment]
that would be good, but don't we want 1-1 parity?

**Comment by marcoscaceres** [comment]
On October 23, 2015 at 9:19:13 PM, mzhilyaev (notifications@github.com) wrote:

> that would be good, but don't we want 1-1 parity?

Yep. Note that some things are labelled "V2". Anything not labelled V2 is for parity.

**Comment by k88hudson** [comment]
:dancer:
