### ISSUE TITLE
Make addon to allow development 

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/remote-newtab#89]
We need a plugin that does this:

```
  imports.RemoteNewTabLocation.override("http://localhost:8000");
```

If it's a plugin, it must be possible to install it automatically on a fresh profile.

**Comment by marcoscaceres** [comment]
Otherwise, we should have a pref that does the above. It's not great at the moment that we have to do the above any time we want to do development on the remote-newtab repo.

**Comment by mzhilyaev** [comment]
Interesting,  I recall adding such pref in one of my early patches to be used with app-cache.
I believe it was removed for security reasons.  I definitely can work on this bug.

**Comment by marcoscaceres** [comment]
Would be great, Max!

**Comment by mzhilyaev** [comment]
but i can't get the browser to talk to my local http server for some
reason.
does it have to be https?

**Comment by marcoscaceres** [comment]
Http is fine, so long as it is "localhost" or "127.0.0.1"

**Comment by oyiptong** [comment]
changing the title to addon. we most definitely don't want a pref, see [bug 1118285](https://bugzilla.mozilla.org/show_bug.cgi?id=1118285)

**Comment by k88hudson** [comment]
Is this still being worked on?

**Comment by oyiptong** [comment]
we do want an addon, and we can do it as soon as https://bugzilla.mozilla.org/show_bug.cgi?id=1218996 lands.

Basically, due to being a prime hijacking target, we can't put the newtab URL in a pref.

We can override it at runtime... or in the source. Doing it at runtime can be done manually, or via an add-on. The add-on would make our lives easier. Shouldn't be hard to write.

**Comment by rlr** [comment]
If your addon can override it at runtime, then any other addon can too. Right?

So then we are back to the same issue of the pref.

**Comment by oyiptong** [comment]
But the security profile is different. Installing an addon is not the same as someone being socially engineered (which is the reason why this is no longer a pref). The full glory: https://bugzilla.mozilla.org/show_bug.cgi?id=1118285

**Comment by oyiptong** [comment]
Also, keep in mind that for testing messages, it's going to be via a pref. This is only for testing the page itself, and probably only used for automated tests.

For testing privileged API's, we're going to allow them on localhost with the use of a pref.

**Comment by rlr** [comment]
Fair enough. I was assuming it was malicious addons that were changing the pref.

**Comment by oyiptong** [comment]
if someone has been able to install an addon, the user is already pretty screwed heh, you are correct

**Comment by marcoscaceres** [comment]
It seems we are all tolerating development without the need of the add-on. Maybe we should just close this?

**Comment by oyiptong** [comment]
I agree. We won't need an addon soon, after bug 1239118 lands. It will allow for localhost development.
